# Generated by Django 5.1.3 on 2024-11-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beuseful', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='johndoeuser', max_length=30),
        ),
    ]
