# Generated by Django 5.1.3 on 2024-11-21 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beuseful', '0002_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
