# Generated by Django 5.1.3 on 2024-12-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beuseful', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Arts', 'Arts'), ('Technology', 'Technology'), ('Educational', 'Educational'), ('Lifestyle', 'Lifestyle'), ('Household', 'Household'), ('Business', 'Business'), ('Misc', 'Misc.')], default='Misc', max_length=50),
        ),
    ]
