# Generated by Django 5.1.3 on 2024-12-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beuseful', '0008_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='beuseful.profile'),
        ),
    ]
